project_id = "czhgnnbkwfbeuqlwizuq"

[functions.letters]
verify_jwt = true

[functions.users]
verify_jwt = true

[functions.dashboard]
verify_jwt = true

[functions.departments]
verify_jwt = true

[functions.auth]
verify_jwt = true